stages:
  - setup
  - test
  - build
  - verify

variables:
  DOCKER_IMAGE: node:8.11.2-stretch
  DOCKER_SEC_TOOLS_IMAGE: registry.gitlab.com/neonexchange/nex-docker-sec-tools:8.11.2

.install_deps: &install_deps |
  yarn --pure-lockfile --cache-folder .yarn

####################
# SETUP
####################

install-deps:
  image: '$DOCKER_IMAGE'
  stage: setup
  tags:
    - nex-cf93d26eada6
  script:
    - *install_deps
  cache:
    untracked: true
    key: '$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG'
    paths:
      - .yarn

####################
# TEST
####################

lint:
  image: '$DOCKER_IMAGE'
  stage: test
  tags:
    - nex-cf93d26eada6
  before_script:
    - *install_deps
  script:
    - yarn test:lint
  cache:
    untracked: true
    policy: pull
    key: '$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG'
    paths:
      - .yarn

unit-test:
  image: '$DOCKER_IMAGE'
  stage: test
  tags:
    - nex-cf93d26eada6
  before_script:
    - *install_deps
  script:
    - yarn test:unit
  cache:
    untracked: true
    policy: pull
    key: '$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG'
    paths:
      - .yarn

####################
# BUILD
####################

build:
  image: '$DOCKER_IMAGE'
  stage: build
  tags:
    - nex-cf93d26eada6
  before_script:
    - *install_deps
  script:
    - yarn build
  cache:
    untracked: true
    policy: pull
    key: '$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG'
    paths:
      - .yarn
  artifacts:
    expire_in: 1 month
    paths:
      - build/

####################
# VERIFY
####################

virus-scan:
  image: '$DOCKER_SEC_TOOLS_IMAGE'
  stage: verify
  tags:
    - nex-cf93d26eada6
  script:
    - nex-vt examine build
  cache: {}
  only:
    - master
  allow_failure: true
